// <auto-generated />
using System;
using MediFlow.ClinicManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediFlow.UsersManagement.Migrations
{
    [DbContext(typeof(UsersManagementDbContext))]
    [Migration("20250801164533_AddMultipleClinicForDoctor")]
    partial class AddMultipleClinicForDoctor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("UsersManagement")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicDoctor", b =>
                {
                    b.Property<Guid>("ClinicsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorsIdsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClinicsId", "DoctorsIdsId");

                    b.HasIndex("DoctorsIdsId");

                    b.ToTable("ClinicDoctor", "UsersManagement");
                });

            modelBuilder.Entity("MediFlow.ClinicManagement.Domain.Entities.Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Clinics", "UsersManagement");
                });

            modelBuilder.Entity("MediFlow.ClinicManagement.Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Doctors", "UsersManagement");
                });

            modelBuilder.Entity("MediFlow.ClinicManagement.Domain.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Fees")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Equipments", "UsersManagement");
                });

            modelBuilder.Entity("MediFlow.ClinicManagement.Domain.Entities.Medicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Medicines", "UsersManagement");
                });

            modelBuilder.Entity("MediFlow.ClinicManagement.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Rooms", "UsersManagement");
                });

            modelBuilder.Entity("ClinicDoctor", b =>
                {
                    b.HasOne("MediFlow.ClinicManagement.Domain.Entities.Clinic", null)
                        .WithMany()
                        .HasForeignKey("ClinicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediFlow.ClinicManagement.Domain.Entities.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorsIdsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediFlow.ClinicManagement.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("MediFlow.ClinicManagement.Domain.Entities.Clinic", null)
                        .WithMany("Equipments")
                        .HasForeignKey("ClinicId");
                });

            modelBuilder.Entity("MediFlow.ClinicManagement.Domain.Entities.Medicine", b =>
                {
                    b.HasOne("MediFlow.ClinicManagement.Domain.Entities.Clinic", null)
                        .WithMany("Medicines")
                        .HasForeignKey("ClinicId");
                });

            modelBuilder.Entity("MediFlow.ClinicManagement.Domain.Entities.Room", b =>
                {
                    b.HasOne("MediFlow.ClinicManagement.Domain.Entities.Clinic", null)
                        .WithMany("Rooms")
                        .HasForeignKey("ClinicId");
                });

            modelBuilder.Entity("MediFlow.ClinicManagement.Domain.Entities.Clinic", b =>
                {
                    b.Navigation("Equipments");

                    b.Navigation("Medicines");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
